language: generic
dist: xenial
sudo: required
script:
- bash fail_test.sh
deploy:
  provider: releases
  api_key:
    secure: Ec49fYBcI32RU4imsmnLLO2Yw72S3WgTKWhQYTOzAsURuxwabj8glISXUwzPGtFByHT7HOzkkKjQ4F4PekTng1mdu4fRm3XgF1Wiu8ZMPrNSFv9lTlTFj3RRnRCi+CwnX4lDLNXBReisoVvpobjCsAMpD7WL/lHzP/BgkcPDkWUZD8RcoUbsSHqNeN5BOPiZfODCKYNNX9P4gmDmR5znoc/a7+1QIxarw5R4349O1aLpBQdCHbbgPtR2CAy6woSaQwTEuPn+oeRLg1n8jjW+U32nooBYX66xfMO4Ofwe70RDPXLYhBnrZIkNSQcJl5zvNOglyCdMJXNZE7xIB3dIpjmNp8TVcTubT77A7XWhIikPymCX42zv8RBa7/f3yt9PntlsGqFcWA6m1VMCrdSpLfO9Y+W+vmFQRQMMjKEB1iSb+SAFvjgYmqMUFeuGoJXL73fxn+cAmJgsV+y1buWrCW4en6bjfPmWR1MNTTttOlf0mK6UAdQJ4uFwGs3GdZw6KvRQWvxD4TcPr+8Y8H2O9lr+Bk/nMgZQM2gvjgxq9OIWUc79Tt0+cmOPhUlCElGm4egvRI1liyNj2Nm4cNZ9IIdplE/0IWP5+bubqx+UZp/s0Cv/7L10yI+8fdqJDtZsySU18l7aCmBvNs8JBGvrIGPgr7shplyvIkXCCMKCdd8=
  file: test.sh
  on:
    repo: galindonkov/fail.sh
    branch: release_adding
